### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by ManuZiD** [ManuZiD/static-code-review-plugin#8]
To let every oncoming commits be reliability and do automatic check.

**Comment by Bwvolleyball** [comment]
Why not give GitHub actions a go? It's just as simple as travis, free for open source projects, but has the added benefit of being fully integrated with your GitHub project.

You might need to sign up for the beta, it will hit GA early - mid November, but it even comes with a Maven starter.  Your GitHub Actions build script could be as simple as:

```xml
name: Maven Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml

```

**Comment by ManuZiD** [comment]
Sounds great! Is that something you could help with?

**Comment by Bwvolleyball** [comment]
Your repository isn't signed up for the beta - you have to get signed up and accepted before GitHub actions can be used.

**Comment by yiss** [comment]
Until the Github actions are implemented on this repository, I added support for Travis CI via #12

**Comment by ManuZiD** [comment]
@yiss thanks for this pr!
